# Generated by Django 5.2 on 2025-05-20 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm',
        ),
        migrations.CreateModel(
            name='Fcm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
