# Generated by Django 5.2 on 2025-06-02 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_fcm_fcm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcms', to=settings.AUTH_USER_MODEL),
        ),
    ]
