# Generated by Django 5.2 on 2025-06-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_fcm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
