# Generated by Django 5.2 on 2025-06-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
