# Generated by Django 5.2 on 2025-07-18 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='second_person',
        ),
        migrations.AddField(
            model_name='conversation',
            name='chatter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatter', to=settings.AUTH_USER_MODEL),
        ),
    ]
