# Generated by Django 5.2 on 2025-07-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_conversation_first_person_and_more'),
        ('products', '0022_alter_product_buyer_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_chatter', to='products.product'),
        ),
    ]
