# Generated by Django 5.2 on 2025-07-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
