# Generated by Django 5.2 on 2025-07-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='admin',
            new_name='support',
        ),
    ]
