from django.urls import path

from .views import (
    changeNameView,
    changeNotificationSettings,
    changeNumberView,
    changePasswordOrResetView,
    checkEmailExistence,
    checkNewEmailExistence,
    deleteAccount,
    fetchMyProducts,
    fetchNotificationsView,
    fetchProfileView,
    listAllUsersView,
    loginView,
    logoutUser,
    registerView,
    sendOtpView,
    sendPublicNotificationView,
    toggleIsFeaturedView,
    toggleUserBlockView,
    verifyOtpView,
)

urlpatterns = [
    path("register/", registerView),
    path("login/", loginView),
    path("logout/", logoutUser),
    path("check_email/", checkEmailExistence),
    path("check_new_email/", checkNewEmailExistence),
    path("delete_account/", deleteAccount),
    path("change_name/", changeNameView),
    path("change_notification_settings/", changeNotificationSettings),
    path("send_otp/", sendOtpView),
    path("verify_otp/", verifyOtpView),
    path("change_number/", changeNumberView),
    path("change_password/", changePasswordOrResetView),
    path("my_products/", fetchMyProducts),
    path("notifications/", fetchNotificationsView),
    path("profile/", fetchProfileView),
    ## ! FOR STAFF ONLY.
    path("send_notification/", sendPublicNotificationView),
    path("list_users/", listAllUsersView.as_view()),
    path("toggle_block/<int:pk>/", toggleUserBlockView),
    path("toggle_featured/<int:pk>/", toggleIsFeaturedView),
]
