# Generated by Django 5.2 on 2025-04-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
