# Generated by Django 5.2 on 2025-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_pages_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pages',
            field=models.IntegerField(),
        ),
    ]
