# Generated by Django 5.2 on 2025-06-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='got_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
