# Generated by Django 5.2 on 2025-06-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_got_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
