# Generated by Django 5.2 on 2025-06-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_appversion_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='appversion',
            options={'ordering': ['-version'], 'verbose_name': 'App Version', 'verbose_name_plural': 'App Versions'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='processinfo',
            options={'verbose_name': 'Process Information', 'verbose_name_plural': 'Process Information'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productstatus',
            options={'ordering': ['status'], 'verbose_name': 'Product Status', 'verbose_name_plural': 'Product Statuses'},
        ),
        migrations.AlterModelOptions(
            name='universityinfo',
            options={'verbose_name': 'University Information', 'verbose_name_plural': 'University Information'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='address',
            name='rest',
            field=models.CharField(max_length=150, verbose_name='Address Details'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Download Link'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(max_length=40, unique=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='processinfo',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='processinfo',
            name='method',
            field=models.CharField(choices=[('donate', 'Donate'), ('sell', 'Sell'), ('lend', 'Lend')], max_length=15, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='processinfo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='processinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_info', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_bought', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='products.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='got_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acquired At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_pending',
            field=models.BooleanField(default=True, verbose_name='Is Pending'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pages',
            field=models.IntegerField(verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstatus', verbose_name='Product Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_sold', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='status',
            field=models.CharField(max_length=30, unique=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='universityinfo',
            name='faculty',
            field=models.CharField(max_length=50, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='universityinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='University Name'),
        ),
        migrations.AlterField(
            model_name='universityinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university_info', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='universityinfo',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
