# Generated by Django 5.2 on 2025-08-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_buyer_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyer',
        ),
    ]
