# Generated by Django 5.2 on 2025-08-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_product_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='got_at',
        ),
    ]
